---
title: "Geometric Morphometric Analysis of Aperture Shapes"
author: "Koji Noshita"
date: "Jan. 2nd, 2021"
output: html_document
---

```{r setup, include=FALSE}
library(here)
library(Momocs)
library(vegan)
library(openxlsx)
library(tibble)
library(ggplot2)
```

## Load outline coordinate values

```{r Load, message=FALSE, warning=FALSE}
DIR_PATH_APERTURE_SHAPES = paste(here::here(),"/data/aperture_shapes/", sep = "")
FILE_LIST = "file_list.csv"

filelist = readr::read_csv(paste(DIR_PATH_APERTURE_SHAPES, FILE_LIST, sep = ""), col_types="cc")
aperture_shape_coo = import_txt(
  c(paste(DIR_PATH_APERTURE_SHAPES, filelist$filename[1:nrow(filelist)], sep=""))
  ,header=FALSE, sep=",",col.names=c("x","y")
  )
aperture_shape_coo = coo_close(Out(aperture_shape_coo))
aperture_shape_coo$fac = tibble(loc = c(1:nrow(filelist)))
aperture_shape_coo$fac$loc = as.factor(filelist$loc) 
```

### Plot aperture shapes

```{r Plot Aperture Shapes}
panel(aperture_shape_coo, fac = "loc", names = TRUE)
```

## Elliptic Fourier analysis

We do not apply normalizaion in this step because  coordinate values have been registered (i.e. standardized in terms of position, direction, and size).

```{r EFA}
aperture_shape_coe <-efourier(aperture_shape_coo, 30, norm = FALSE)
```

### PCA

To sumurize the result of EFA, we can conduct PCA.

```{r PCA}
aperture_shape_pca <- PCA(aperture_shape_coe)
```

And, plot the result.

```{r PCA Plot}
plot(aperture_shape_pca, ~loc, morphospace_position = "full")
```

### MANOVA

```{r MANOVA}
MANOVA(aperture_shape_pca, ~loc, test = "Pillai", retain=0.99)
```
